AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Payments

Parameters:
Globals:
  Function:
    Timeout: 5
    MemorySize: 512

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    MethodSettings:
      - LoggingLevel: INFO
        ResourcePath: "/*"
        HttpMethod: "*"
    Properties:
      StageName: test
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
        MaxAge: "'600'"

  PaymentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: ID
          AttributeType: S
      KeySchema:
        - AttributeName: ID
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  GetPaymentsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist
      Handler: handlers/paymentHandler.getPayments
      Runtime: nodejs18.x
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref PaymentsTable
      Environment:
        Variables:
          DB_TABLE: !Ref PaymentsTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: GET

  PostPaymentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist
      Handler: handlers/paymentHandler.postPayment
      Runtime: nodejs18.x
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref PaymentsTable
      Environment:
        Variables:
          DB_TABLE: !Ref PaymentsTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: POST
